########
#
########
server:
  port: 8081

#
spring:
  application:
    name: oauth-client
#
security:
  user:
    password: password
  oauth2:
    resource:
      user-info-uri: http://localhost:8080/i/info.html
    client:
      resource-ids: app
      user-authorization-uri: http://localhost:8080/oauth/authorize
      access-token-uri: http://localhost:8080/oauth/token
      client-id: client
      client-secret: password
#
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.18:8761/eureka/
  instance:
#    ip-address: 192.168.1.220
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port:8080}

#