########
#
########
server:
  port: 8082

#
spring:
  application:
    name: OAUTH-CLIENT
#
security:
  user:
    password: password
  oauth2:
    host: http://oauth-server
    resource:
      service-id: demo-resources
      token-info-uri: ${security.oauth2.host}/oauth/check_token
#      user-info-uri: ${security.oauth2.host}/i/info.html
    client:
      access-token-uri: ${security.oauth2.host}/oauth/token
      client-id: demo-client
      client-secret: password
#
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
#    ip-address: 192.168.1.220
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port:8080}

#