########
#
########
server:
  port: 8080
spring:
  application:
    name: ico-demo
#
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
#    ip-address: 192.168.1.220
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port:8080}

#