########
#
########
server:
  port: 8080
spring:
  application:
    name: serv
#
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.18:8761/eureka/
  instance:
#    ip-address: 192.168.1.220
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port:8080}
#
security:
  user:
    password: d444974b5614
#
