###
#
###
server:
  port: 8761

#
spring:
  application:
    name: euk
    
#
eureka:
  instance:
    hostname: def
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port:8761}/eureka/

#

