########
#
########
server:
  port: 8081

#
spring:
  application:
    name: OAUTH-CLIENT
#
security:
  user:
    name: oauth-client
    password: password
  oauth2:
    resource:
      token-info-uri: ${security.oauth2.host}/oauth/check_token
    host: http://OAUTH-SERVER
    client:
      client-id: demo-client
      client-secret: password
      access-token-uri: ${security.oauth2.host}/oauth/token
      user-authorization-uri: ${security.oauth2.host}/oauth/authorize
#
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port:8080}

#